version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "4306:3306"
  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/west-chiba-gurume-map
    ports:
      - "3035:3035"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/west-chiba-gurume-map
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
